---
- name: Install Jenkins
  hosts: jenkins
  become: true

  tasks:
  - name: Download Long Term Jenkins release
    get_url:
      url: https://pkg.jenkins.io/redhat-stable/jenkins.repo
      dest: /etc/yum.repos.d/jenkins.repo

  - name: Import jenkins key from url
    ansible.builtin.rpm_key:
      state: present
      key: https://pkg.jenkins.io/redhat-stable/jenkins.io.key

  - name: Install java
    yum:
      name: java-11-openjdk-devel
      state: present

  - name: Install jenkins
    yum:
      name: jenkins
      state: latest

  - name: daemon-reload to pick up config changes
    ansible.builtin.systemd:
      daemon_reload: yes

  - name: Start jenkins
    ansible.builtin.systemd:
      name: jenkins
      state: started

  - name: Wait for Jenkins to start
    wait_for:
      host: localhost
      port: 8080
      state: started

  - name: get admin pass
    command: cat /var/lib/jenkins/secrets/initialAdminPassword
    register: adminpass

  - name: print pass
    debug: msg="{{ adminpass.stdout_lines }}"